netty:
  netMsgNameSpace: com.hc.nettygame.common.message.logic
  gameExecutorCorePoolSize: 4
  tcpMessageQueueDirectDispatch: false
  rpcOpen: true
  rpcThreadPoolSize: 60
  rpcThreadPoolQueueSize: 65536
  rpcConnectThreadSize: 16
  rpcSendProxyThreadSize: 16
  rpcTimeOut: 0
  rpcFutureDeleteTimeOut: 60*1000
management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露Actuator的监控端点
  endpoint:
    health:
      show-details: always #显示健康的详细信息
    env:
      show-values: always #默认Actuator的环境变量会以****显示，这里开启显示
    configprops:
      show-values: always #默认Actuator的配置属性会以****显示，这里开启显示
    info:
      enabled: true
rpc:
  sdRpcServiceProvider:
    servers:
      - gate
      - node
      - world
  sdGateServers:
    - serverId: 8001
      domain: 127.0.0.1
      domainPort: 7090
      ip: 127.0.0.1
      port: 7090
      weight: 100
      maxNumber: 1000
      rpcPort: 10100
      rpcClientNumber: 3
  sdNodeServers:
    - serverId: 8001
      domain: 127.0.0.1
      domainPort: 7090
      ip: 127.0.0.1
      port: 7090
      weight: 100
      maxNumber: 1000
      rpcPort: 10100
      rpcClientNumber: 3
  sdWorldServers:
    - serverId: 8001
      domain: 127.0.0.1
      domainPort: 7090
      ip: 127.0.0.1
      port: 7090
      weight: 100
      maxNumber: 1000
      rpcPort: 10100
      rpcClientNumber: 3
