// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tcp_client.proto

package com.hc.nettygame.generatecode.message.auto.tcp.client;

public final class TcpClientMessageProBuf {
  private TcpClientMessageProBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OnlineHeartTcpClientProBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OnlineHeartTcpClientProBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code OnlineHeartTcpClientProBuf}
   */
  public static final class OnlineHeartTcpClientProBuf extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OnlineHeartTcpClientProBuf)
      OnlineHeartTcpClientProBufOrBuilder {
    // Use OnlineHeartTcpClientProBuf.newBuilder() to construct.
    private OnlineHeartTcpClientProBuf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OnlineHeartTcpClientProBuf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OnlineHeartTcpClientProBuf defaultInstance;
    public static OnlineHeartTcpClientProBuf getDefaultInstance() {
      return defaultInstance;
    }

    public OnlineHeartTcpClientProBuf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OnlineHeartTcpClientProBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineHeartTcpClientProBuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineHeartTcpClientProBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf.class, com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf.Builder.class);
    }

    public static com.google.protobuf.Parser<OnlineHeartTcpClientProBuf> PARSER =
        new com.google.protobuf.AbstractParser<OnlineHeartTcpClientProBuf>() {
      public OnlineHeartTcpClientProBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnlineHeartTcpClientProBuf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OnlineHeartTcpClientProBuf> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OnlineHeartTcpClientProBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OnlineHeartTcpClientProBuf)
        com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineHeartTcpClientProBuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineHeartTcpClientProBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf.class, com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf.Builder.class);
      }

      // Construct using com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineHeartTcpClientProBuf_descriptor;
      }

      public com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf getDefaultInstanceForType() {
        return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf.getDefaultInstance();
      }

      public com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf build() {
        com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf buildPartial() {
        com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf result = new com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf) {
          return mergeFrom((com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf other) {
        if (other == com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineHeartTcpClientProBuf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OnlineHeartTcpClientProBuf)
    }

    static {
      defaultInstance = new OnlineHeartTcpClientProBuf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OnlineHeartTcpClientProBuf)
  }

  public interface OnlineLoginTcpClientProBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OnlineLoginTcpClientProBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code OnlineLoginTcpClientProBuf}
   */
  public static final class OnlineLoginTcpClientProBuf extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OnlineLoginTcpClientProBuf)
      OnlineLoginTcpClientProBufOrBuilder {
    // Use OnlineLoginTcpClientProBuf.newBuilder() to construct.
    private OnlineLoginTcpClientProBuf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OnlineLoginTcpClientProBuf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OnlineLoginTcpClientProBuf defaultInstance;
    public static OnlineLoginTcpClientProBuf getDefaultInstance() {
      return defaultInstance;
    }

    public OnlineLoginTcpClientProBuf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OnlineLoginTcpClientProBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineLoginTcpClientProBuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineLoginTcpClientProBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf.class, com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf.Builder.class);
    }

    public static com.google.protobuf.Parser<OnlineLoginTcpClientProBuf> PARSER =
        new com.google.protobuf.AbstractParser<OnlineLoginTcpClientProBuf>() {
      public OnlineLoginTcpClientProBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnlineLoginTcpClientProBuf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OnlineLoginTcpClientProBuf> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OnlineLoginTcpClientProBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OnlineLoginTcpClientProBuf)
        com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineLoginTcpClientProBuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineLoginTcpClientProBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf.class, com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf.Builder.class);
      }

      // Construct using com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.internal_static_OnlineLoginTcpClientProBuf_descriptor;
      }

      public com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf getDefaultInstanceForType() {
        return com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf.getDefaultInstance();
      }

      public com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf build() {
        com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf buildPartial() {
        com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf result = new com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf) {
          return mergeFrom((com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf other) {
        if (other == com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hc.nettygame.generatecode.message.auto.tcp.client.TcpClientMessageProBuf.OnlineLoginTcpClientProBuf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OnlineLoginTcpClientProBuf)
    }

    static {
      defaultInstance = new OnlineLoginTcpClientProBuf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OnlineLoginTcpClientProBuf)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OnlineHeartTcpClientProBuf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OnlineHeartTcpClientProBuf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OnlineLoginTcpClientProBuf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OnlineLoginTcpClientProBuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020tcp_client.proto\"(\n\032OnlineHeartTcpClie" +
      "ntProBuf\022\n\n\002id\030\001 \002(\005\"(\n\032OnlineLoginTcpCl" +
      "ientProBuf\022\n\n\002id\030\001 \002(\005BO\n5com.hc.nettyga" +
      "me.generatecode.message.auto.tcp.clientB" +
      "\026TcpClientMessageProBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OnlineHeartTcpClientProBuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OnlineHeartTcpClientProBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OnlineHeartTcpClientProBuf_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_OnlineLoginTcpClientProBuf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OnlineLoginTcpClientProBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OnlineLoginTcpClientProBuf_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
