// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tcp_server.proto

package com.hc.nettygame.common.message.auto.tcp.server;

public final class TcpServerMessageProBuf {
  private TcpServerMessageProBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OnlineLoginTcpServerProBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OnlineLoginTcpServerProBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int64 playerId = 1;</code>
     */
    long getPlayerId();

    /**
     * <code>required int32 token = 2;</code>
     */
    boolean hasToken();
    /**
     * <code>required int32 token = 2;</code>
     */
    int getToken();
  }
  /**
   * Protobuf type {@code OnlineLoginTcpServerProBuf}
   */
  public static final class OnlineLoginTcpServerProBuf extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OnlineLoginTcpServerProBuf)
      OnlineLoginTcpServerProBufOrBuilder {
    // Use OnlineLoginTcpServerProBuf.newBuilder() to construct.
    private OnlineLoginTcpServerProBuf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OnlineLoginTcpServerProBuf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OnlineLoginTcpServerProBuf defaultInstance;
    public static OnlineLoginTcpServerProBuf getDefaultInstance() {
      return defaultInstance;
    }

    public OnlineLoginTcpServerProBuf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OnlineLoginTcpServerProBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              token_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.internal_static_OnlineLoginTcpServerProBuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.internal_static_OnlineLoginTcpServerProBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf.class, com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf.Builder.class);
    }

    public static com.google.protobuf.Parser<OnlineLoginTcpServerProBuf> PARSER =
        new com.google.protobuf.AbstractParser<OnlineLoginTcpServerProBuf>() {
      public OnlineLoginTcpServerProBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnlineLoginTcpServerProBuf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OnlineLoginTcpServerProBuf> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>required int64 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private int token_;
    /**
     * <code>required int32 token = 2;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 token = 2;</code>
     */
    public int getToken() {
      return token_;
    }

    private void initFields() {
      playerId_ = 0L;
      token_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, token_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, token_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OnlineLoginTcpServerProBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OnlineLoginTcpServerProBuf)
        com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.internal_static_OnlineLoginTcpServerProBuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.internal_static_OnlineLoginTcpServerProBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf.class, com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf.Builder.class);
      }

      // Construct using com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.internal_static_OnlineLoginTcpServerProBuf_descriptor;
      }

      public com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf getDefaultInstanceForType() {
        return com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf.getDefaultInstance();
      }

      public com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf build() {
        com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf buildPartial() {
        com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf result = new com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf) {
          return mergeFrom((com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf other) {
        if (other == com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasToken()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hc.nettygame.common.message.auto.tcp.server.TcpServerMessageProBuf.OnlineLoginTcpServerProBuf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long playerId_ ;
      /**
       * <code>required int64 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private int token_ ;
      /**
       * <code>required int32 token = 2;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public int getToken() {
        return token_;
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public Builder setToken(int value) {
        bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OnlineLoginTcpServerProBuf)
    }

    static {
      defaultInstance = new OnlineLoginTcpServerProBuf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OnlineLoginTcpServerProBuf)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OnlineLoginTcpServerProBuf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OnlineLoginTcpServerProBuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020tcp_server.proto\"=\n\032OnlineLoginTcpServ" +
      "erProBuf\022\020\n\010playerId\030\001 \002(\003\022\r\n\005token\030\002 \002(" +
      "\005BI\n/com.hc.nettygame.common.message.aut" +
      "o.tcp.serverB\026TcpServerMessageProBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OnlineLoginTcpServerProBuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OnlineLoginTcpServerProBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OnlineLoginTcpServerProBuf_descriptor,
        new java.lang.String[] { "PlayerId", "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
